- name: '[system] Install default configurations'
  ansible.builtin.template:
    src: vimrc.j2
    dest: "{{ vim_root_config }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - vim
    
- name: '[system] Install default plugins'
  ansible.builtin.template:
    src: vimrc.bundles.j2
    dest: "{{ vim_root_bundles }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - vim
  register: plugins_config

- name: '[system] Install vimrc.recommended'
  ansible.builtin.template:
    src: vimrc.recommended.j2
    dest: "{{ vim_root_recommended }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - vim

- name: '[system] Install Vundle'
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /var/lib/vim/addons/Vundle.vim
    version: "{{ vim_vundle_version }}"
    force: true
  tags:
    - vim

- name: '[system] Downloads plugins'
  ansible.builtin.command: vim +PluginInstall +qal
  changed_when: false # 
  when: plugins_config.changed
  tags:
    - vim