- name: Make sure vim-tiny is uninstalled
  ansible.builtin.apt:
    name: vim-tiny
    state: absent
    purge: true
  tags:
    - vim

- name: Make sure vim-nox is installed
  ansible.builtin.apt:
    name: vim-nox
    state: present
  tags:
    - vim

- name: Install CTags
  ansible.builtin.apt:
    name: exuberant-ctags
    state: present
  tags:
    - vim
